Robusta
metosin/spec-swagger pull request #9
Opened 2017-06-27 08:32 UTC by ikitommi

* Update to latest spec-tools
* test all known types (as schemas)
* s/or and s/and in with x-oneOf and x-allOf
* body-parameter requirement from s/nilable
* body-parameter name from spec-name
* merge core & schema namespaces

2017-06-27 08:57 UTC, miikka requested changes
I don't think that the code is generating valid Swagger 2.0 schemas. (Maybe it wasn't generating them before this change, either.)

2017-06-27 08:57 UTC, miikka commented on README.md
> +**NOTE**: As `clojure.spec` is more powerfull than the Swagger2 JSON Schema, we are losing some data in the transformation. Spec-swagger tries to retain all the informatin, via vendor extensions.
[nit] powerfull -> powerful

2017-06-27 08:57 UTC, miikka commented on README.md
> +
Would be useful to explain what these options do.

2017-06-27 08:57 UTC, miikka commented on project.clj
> +                                  [org.clojure/clojurescript "1.9.562"]
1.9.655 is just out!

2017-06-27 08:57 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +    (first children)
I'm reading the Swagger 2.0 spec and I no longer believe that `{:type ["number", "string"]}` is valid. That said, using the first child does not make any sense to me. Doesn't it mean that the types of the further children are then illegal?

2017-06-27 08:57 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +  (assoc
The same comment about the first child applies here.

2017-06-27 08:57 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +   :items (assoc
The same comment about the first child applies here.

2017-06-27 08:57 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +   :maxItems (count children)
I'm now thinking that these counts are in fact wrong, because inside cat you can use regular expressions.

2017-06-27 08:57 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +   :items [(first children)]
According to the Swagger 2.0 spec, `items` must be an object, not an array. The same comment about the first child applies here.

2017-06-27 13:03 UTC, ikitommi commented on README.md
> +
did.

2017-06-27 13:08 UTC, ikitommi commented on src/spec_swagger/swagger2/core.cljc
> +    (first children)
We have option to either:

1) use a convention to produce api-docs that can help to create valid requests. This fulfils the purpose: the first value is a valid value and an api-doc client & ui can be generated (but not all valid values can be sent via them). Using the first value is a convention from Schema & Ring-swagger, e.g. `(s/conditional s/Int pos?)` is an `s/Int` with some extra stuff on the tail.

2) we say "anything goes", but we produce invalid swagger spec (parameters need to have a type).

I would go with 1.

2017-06-27 13:08 UTC, ikitommi commented on src/spec_swagger/swagger2/core.cljc
> +   :maxItems (count children)
Good catch! Fixed those also on the spec-tools side.

2017-06-27 13:16 UTC, ikitommi commented
changed `s/tuple` to return `{}` as we can't figure out it's form. Others I think are fine.

2017-06-27 13:20 UTC, ikitommi commented on project.clj
> +                                  [org.clojure/clojurescript "1.9.562"]
With the new  `resolve`, it needs some work on `spec-tools`. Would you like to do the honors? Also, there were some patches to spec that might not yet be in `clojure.spec`?

2017-06-27 14:10 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +   :items [(first children)]
"`items` must be an object" still applies

2017-06-27 14:10 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +    (first children)
The first value convention makes perfect sense for and-type conditions like `(s/conditional s/Int pos?)`, but not for or-type conditions.
* If your endpoint only takes a positive int and the docs say you can use any int, that's fine. If you send a negative int, you'll get hopefully-helpful error message.
* If your endpoint takes an int or a string, the docs say that you can only send an int and there's no way to discover that strings would be fine, too.

I didn't realize that type is required, but you're right. There's no good answer. Let's go with 1, then, at least it produces valid specs.

The Swagger 2.0 schema language is just too limited. Maybe OpenAPI 3.0 will save us.

2017-06-27 18:02 UTC, ikitommi commented on src/spec_swagger/swagger2/core.cljc
> +   :items [(first children)]
changed to `{}`

2017-06-27 18:04 UTC, ikitommi commented
still something to do @miikka ?

2017-06-27 18:52 UTC, miikka approved these changes
Okay, so I probably just have to give up on the idea of actually producing Swagger 2.0 -compatible schemas for clojure.specs.

2017-06-27 18:52 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +   :items {}
Right, so it's not enough for it to be an empty object, it also has to contain `:type`. I don't know what to do here.

2017-06-27 20:28 UTC, ikitommi commented on src/spec_swagger/swagger2/core.cljc
> +   :items {}
I believe that the generated schemas are all swagger2 compatible and all generated schemas are now validated with ring-swagger validator. Or did I miss something?

Another story is that not all generated schemas are not fully accurate as they present only a subset on available values.

2017-06-27 20:29 UTC, ikitommi commented
Thanks for the review!

2017-06-27 20:29 UTC, merged

2017-06-28 05:07 UTC, miikka commented on src/spec_swagger/swagger2/core.cljc
> +   :items {}
Aha, I've mixed up the specs for body and the parameters. That explains why the specification seemed so different from what I was remembering. This isn't a valid parameter specification but it's valid in body.